"""empty message

Revision ID: 15c70df56301
Revises: 2ff479367415
Create Date: 2023-02-03 12:56:03.382411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c70df56301'
down_revision = '2ff479367415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('sire_id', sa.Integer(), nullable=True),
    sa.Column('dam_id', sa.Integer(), nullable=True),
    sa.Column('reg_name', sa.String(length=255), nullable=False),
    sa.Column('reg_number', sa.String(length=255), nullable=True),
    sa.Column('call_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.Column('breed_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('head_size', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('titles', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['dam_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sire_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_name'),
    sa.UniqueConstraint('reg_number')
    )
    op.create_table('user_dog',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_dog')
    op.drop_table('dogs')
    op.drop_table('colors')
    op.drop_table('breeds')
    # ### end Alembic commands ###
