"""empty message

Revision ID: 0cfe011120be
Revises: 15c70df56301
Create Date: 2023-02-06 08:44:49.472336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfe011120be'
down_revision = '15c70df56301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dogs', 'img_url')
    # ### end Alembic commands ###
